//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.07.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace Digma.Rider.Protocol
{
  
  
  /// <summary>
  /// <p>Generated from: MethodInfoModel.kt:9</p>
  /// </summary>
  public class MethodInfoModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<Unit, MethodInfo> GetMethodUnderCaret => _GetMethodUnderCaret;
    
    //private fields
    [NotNull] private readonly RdCall<Unit, MethodInfo> _GetMethodUnderCaret;
    
    //primary constructor
    private MethodInfoModel(
      [NotNull] RdCall<Unit, MethodInfo> getMethodUnderCaret
    )
    {
      if (getMethodUnderCaret == null) throw new ArgumentNullException("getMethodUnderCaret");
      
      _GetMethodUnderCaret = getMethodUnderCaret;
      BindableChildren.Add(new KeyValuePair<string, object>("getMethodUnderCaret", _GetMethodUnderCaret));
    }
    //secondary constructor
    internal MethodInfoModel (
    ) : this (
      new RdCall<Unit, MethodInfo>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid, MethodInfo.Read, MethodInfo.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => 4524857110976482394L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(JetBrains.Rider.Model.IdeRoot), JetBrains.Rider.Model.IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("MethodInfoModel (");
      using (printer.IndentCookie()) {
        printer.Print("getMethodUnderCaret = "); _GetMethodUnderCaret.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionMethodInfoModelEx
   {
    public static MethodInfoModel GetMethodInfoModel(this JetBrains.Rider.Model.Solution solution)
    {
      return solution.GetOrCreateExtension("methodInfoModel", () => new MethodInfoModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: MethodInfoModel.kt:11</p>
  /// </summary>
  public sealed class MethodInfo : IPrintable, IEquatable<MethodInfo>
  {
    //fields
    //public fields
    [NotNull] public string Fqn {get; private set;}
    [NotNull] public string FilePath {get; private set;}
    
    //private fields
    //primary constructor
    public MethodInfo(
      [NotNull] string fqn,
      [NotNull] string filePath
    )
    {
      if (fqn == null) throw new ArgumentNullException("fqn");
      if (filePath == null) throw new ArgumentNullException("filePath");
      
      Fqn = fqn;
      FilePath = filePath;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string fqn, [NotNull] out string filePath)
    {
      fqn = Fqn;
      filePath = FilePath;
    }
    //statics
    
    public static CtxReadDelegate<MethodInfo> Read = (ctx, reader) => 
    {
      var fqn = reader.ReadString();
      var filePath = reader.ReadString();
      var _result = new MethodInfo(fqn, filePath);
      return _result;
    };
    
    public static CtxWriteDelegate<MethodInfo> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Fqn);
      writer.Write(value.FilePath);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MethodInfo) obj);
    }
    public bool Equals(MethodInfo other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Fqn == other.Fqn && FilePath == other.FilePath;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Fqn.GetHashCode();
        hash = hash * 31 + FilePath.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MethodInfo (");
      using (printer.IndentCookie()) {
        printer.Print("fqn = "); Fqn.PrintEx(printer); printer.Println();
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
