name: 'Workflow setup'
description: 'Setup the workflow environment and tools'
runs:
  using: "composite"
  steps:

    - name: Setup Java
      uses: ./github-actions/java-setup

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.301
