  NOT IN USE
name: 'Validate posthog url'
description: 'Validate posthog url'
inputs:
  build-profile:
    description: 'the current build profile'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Export Version
      id: exportversion
      shell: bash
      run: |
        VERSION=$(cat version.properties |grep "version="|cut -d= -f2)
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

    - name: Find posthog url
      id: posthog
      shell: bash
      run: |
        IJ_RELEASE_NUMBER=$(echo "${{ inputs.build-profile }}"|cut -c 2-)
        cd ${{ github.workspace }}/build/libs
        FILENAME=`ls digma-intellij-plugin-${{ steps.exportversion.outputs.version }}+$IJ_RELEASE_NUMBER.jar`
        unzip -q "$FILENAME" -d content
        URL=$(cat ./content/posthog-token-url.txt)
        echo "url=${URL}" >> "$GITHUB_OUTPUT"

    - name: Debug posthog url
      if: ${{ steps.posthog.outputs.url == '' }}
      shell: bash
      run: echo "posthog url is empty,failing build"

    - name: Verify posthog url exists
      if: ${{ steps.posthog.outputs.url == '' }}
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed('posthog url is empty')
