## This workflow runs plugin verifier. plugin verifier requires a bit more disk space than regular build.
## So the workflow uses a modified maximize-build-space,AdityaGarg8/remove-unwanted-software, action that only removed
##  some software.
##  the original easimon/maximize-build-space action causes builds to fails for some reason and also requires executing
##  gralde  with modified cache locations like '--gradle-user-home=./.localhome --project-cache-dir=./.projectcache'.
##  AdityaGarg8/remove-unwanted-software frees around 12G of disk space.
## No need to run gradle/wrapper-validation-action because this workflow does not produce artifacts.
##  and gradle/wrapper-validation-action tends to fail a lot.

name: Run plugin verifier

on:
  workflow_call:
    inputs:
      build-profile:
        required: true
        type: string
      ref-name:
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
          remove-large-packages: true
          remove-cached-tools: true
          remove-swapfile: true

      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref-name }}

      - name: Workflow setup
        uses: ./github-actions/workflow-setup


      - name: Run Plugin Verifier
        run: ./gradlew buildPlugin verifyPlugin -PbuildProfile=${{ inputs.build-profile }}

      - name: Collect Plugin Verifier Result
        if: ${{ inputs.build-with-rider != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: pluginVerifier-result-${{ inputs.build-profile }}
          path: ${{ github.workspace }}/build/reports/pluginVerifier
          retention-days: 5

