# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and RunPluginVerifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
             6.0.102
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        gradle-home-cache-excludes: |
            caches/**/riderRD-*/**
            caches/**/ideaIC-*/**
            caches/**/pycharmPC-*/**
        arguments: runPluginVerifier buildPlugin
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with:
        name: digma-intellij-plugin
        path: build/distributions/digma-intellij-1.0.3.zip
